#!/usr/bin/env bash
# Deploy ai-gateway on rainbowone.
# Idempotent: re-running pulls latest upstream main, keeps .env and ./data
# untouched, rebuilds, restarts.
#
# compose overlay + this script are host-local (not tracked upstream). The
# canonical copies live at /home/yoav/ai-gateway-deploy/ and are copied into the
# checkout on every run, so edits belong here, not in ~/ai-gateway.
set -euo pipefail

DIR=/home/yoav/ai-gateway
REPO=https://github.com/karutoil/ai-gateway.git
BRANCH=main
HOST_PORT=8090
PUBLIC_URL=http://100.99.145.19:${HOST_PORT}
SELF_DIR="$(cd "$(dirname "$0")" && pwd)"
COMPOSE_ARGS=(-f docker-compose.yml -f docker-compose.rainbowone.yml)

if [ ! -d "$DIR/.git" ]; then
  echo "==> cloning $REPO into $DIR"
  git clone --branch "$BRANCH" "$REPO" "$DIR"
else
  echo "==> updating existing checkout"
  git -C "$DIR" fetch origin "$BRANCH"
  git -C "$DIR" reset --hard "origin/$BRANCH"
fi

cd "$DIR"
mkdir -p data

echo "==> syncing deploy files from $SELF_DIR"
cp "$SELF_DIR/docker-compose.rainbowone.yml" "$DIR/docker-compose.rainbowone.yml"
cp "$SELF_DIR/deploy.sh" "$DIR/deploy.sh"
chmod +x "$DIR/deploy.sh"
# Stale hand-edited backup from before the !override fix; would be picked up by
# an accidental `-f *.yml` glob, so drop it.
rm -f "$DIR/docker-compose.rainbowone.yml.bak"

if [ ! -f .env ]; then
  echo "==> generating .env with fresh secrets"
  umask 077
  cat > .env <<EOF
# Generated by deploy.sh — secrets are unique to this host. Do not commit.
ENV=production
PORT=8080
ADMIN_PASSWORD=$(openssl rand -base64 18 | tr -d '/+=' | cut -c1-20)
MASTER_KEY=$(openssl rand -hex 32)
JWT_SECRET=$(openssl rand -hex 48)
PUBLIC_URL=${PUBLIC_URL}
CORS_ALLOWED_ORIGINS=${PUBLIC_URL},http://localhost:${HOST_PORT}
DATABASE_URL=/data/gateway.db
LOG_RETENTION_DAYS=30
EOF
  chmod 600 .env
else
  echo "==> keeping existing .env"
fi

# A base-file port mapping the overlay forgot to override makes the container
# fail to start with "port is already allocated" (compose would render two
# entries for target 8080). `config` renders long form with block-sequence
# indentation that varies by compose version, so count the "- mode:" list items
# under the gateway ports key instead of matching fixed indentation.
port_count=$(docker compose "${COMPOSE_ARGS[@]}" config \
  | awk '/^[[:space:]]*ports:[[:space:]]*$/{inports=1; next}
         inports && /^[[:space:]]*-[[:space:]]*mode:/{c++; next}
         inports && /^[[:space:]]*[a-z_-]+:/{inports=0}
         END{print c+0}')
if [ "$port_count" != "1" ]; then
  echo "!! expected exactly 1 published port mapping, got ${port_count} — check the !override tag" >&2
  exit 1
fi
if ! docker compose "${COMPOSE_ARGS[@]}" config | grep -q 'published: "8090"'; then
  echo "!! compose config does not publish host port 8090" >&2
  exit 1
fi

echo "==> building image"
docker compose "${COMPOSE_ARGS[@]}" build

echo "==> starting stack"
docker compose "${COMPOSE_ARGS[@]}" up -d

echo "==> waiting for readiness"
for i in $(seq 1 60); do
  if curl -fsS -o /dev/null --max-time 3 "${PUBLIC_URL}/health"; then
    echo "==> healthy after ${i}s"
    break
  fi
  sleep 1
done

docker compose "${COMPOSE_ARGS[@]}" ps
echo "==> done: ${PUBLIC_URL}"
