#!/usr/bin/env bash
# Deploy ai-gateway on rainbowone.
# Idempotent: re-running pulls latest main, keeps .env and ./data untouched,
# rebuilds, restarts.
#
# Source of truth for both the compose overlay and this script is the fork at
# phantomic12/ai-gateway; both files live at the repo root. Do not hand-edit the
# copies under ~/ai-gateway — this script overwrites them on every run.
set -euo pipefail

DIR=/home/yoav/ai-gateway
REPO=https://github.com/phantomic12/ai-gateway.git
BRANCH=main
HOST_PORT=8090
PUBLIC_URL=http://100.99.145.19:${HOST_PORT}
COMPOSE_ARGS=(-f docker-compose.yml -f docker-compose.rainbowone.yml)

if [ ! -d "$DIR/.git" ]; then
  echo "==> cloning $REPO into $DIR"
  git clone --branch "$BRANCH" "$REPO" "$DIR"
else
  echo "==> updating existing checkout"
  git -C "$DIR" fetch origin "$BRANCH"
  git -C "$DIR" reset --hard "origin/$BRANCH"
fi

cd "$DIR"
mkdir -p data

echo "==> syncing deploy files from $(dirname "$0")"
# Tracked in the fork, so a reset --hard may already have refreshed them; copy
# anyway so this script also works when run from a stale checkout elsewhere.
for f in docker-compose.rainbowone.yml; do
  if [ -f "$(dirname "$0")/$f" ]; then
    cp "$(dirname "$0")/$f" "$DIR/$f"
  fi
done
rm -f "$DIR/docker-compose.rainbowone.yml.bak"

# Legacy hand-copied deployment dir: superseded by the files now tracked in the
# repo root. Kept as a redirect so older muscle memory does not run a stale copy.
if [ -d /home/yoav/ai-gateway-deploy ]; then
  cat > /home/yoav/ai-gateway-deploy/README.md <<'EOF'
Superseded. The deployment overlay (docker-compose.rainbowone.yml) and deploy.sh
now live in the repo root and are tracked in phantomic12/ai-gateway.

Run: bash /home/yoav/ai-gateway/deploy.sh
EOF
fi

if [ ! -f .env ]; then
  echo "==> generating .env with fresh secrets"
  umask 077
  cat > .env <<EOF
# Generated by deploy.sh — secrets are unique to this host. Do not commit.
ENV=production
PORT=8080
ADMIN_PASSWORD=$(openssl rand -base64 18 | tr -d '/+=' | cut -c1-20)
MASTER_KEY=$(openssl rand -hex 32)
JWT_SECRET=$(openssl rand -hex 48)
PUBLIC_URL=${PUBLIC_URL}
CORS_ALLOWED_ORIGINS=${PUBLIC_URL},http://localhost:${HOST_PORT}
DATABASE_URL=/data/gateway.db
LOG_RETENTION_DAYS=30
EOF
  chmod 600 .env
else
  echo "==> keeping existing .env"
fi

# A base-file port mapping the overlay forgot to override makes the container
# fail to start with "port is already allocated". Fail loudly instead of leaving
# a half-up stack behind.
if ! docker compose "${COMPOSE_ARGS[@]}" config | grep -q '"8090:8080"'; then
  echo "!! compose config does not expose 8090:8080 — check the !override tag" >&2
  exit 1
fi

echo "==> building image"
docker compose "${COMPOSE_ARGS[@]}" build

echo "==> starting stack"
docker compose "${COMPOSE_ARGS[@]}" up -d

echo "==> waiting for readiness"
for i in $(seq 1 60); do
  if curl -fsS -o /dev/null --max-time 3 "${PUBLIC_URL}/health"; then
    echo "==> healthy after ${i}s"
    break
  fi
  sleep 1
done

docker compose "${COMPOSE_ARGS[@]}" ps
echo "==> done: ${PUBLIC_URL}"
